# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure('2') do |config|
    config.vm.box = "dummy"
    config.ssh.pty = "true"

    config.vm.provider :aws do |aws, override|
        # Secrets
        aws.access_key_id = ENV["AWS_ACCESS_KEY"]
        aws.secret_access_key = ENV["AWS_SECRET_KEY"]
        aws.keypair_name = "yzguy"
        
        # Connection information
        override.ssh.username = "ec2-user"
        override.ssh.private_key_path = "~/.ssh/yzguy.pem"
        
        # Instance settings
        aws.ami = "ami-1ecae776"
        aws.instance_type = "t2.micro"
        aws.region = "us-east-1"
        aws.security_groups = ["sg-ea91368d"]
        aws.subnet_id = "subnet-5196d408"
        aws.associate_public_ip = "true"

        # Turn off requring a tty so functionality works
        aws.user_data = "#!/bin/bash\nsed -i -e 's/^Defaults.*requiretty/# Defaults requiretty/g' /etc/sudoers"
    end
end
