- hosts: vagrant

  tasks:
    - name: Install Bind DNS server
      apt: name=bind9 state=present

    - name: Setup named.conf.local file
      template: src=templates/slave/named.conf.local.j2 dest=/etc/bind/named.conf.local owner=root group=bind mode=0644

    - name: Setup named.conf.options file
      template: src=templates/slave/named.conf.options.j2 dest=/etc/bind/named.conf.options owner=root group=bind mode=0644
    
    - name: Ensure bind9 is running
      service: name=bind9 state=started enabled=yes
